//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbMyOnlineShoppingEntities1 : DbContext
    {
        public dbMyOnlineShoppingEntities1()
            : base("name=dbMyOnlineShoppingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AUDIT> tbl_AUDIT { get; set; }
        public virtual DbSet<Tbl_Cart> Tbl_Cart { get; set; }
        public virtual DbSet<Tbl_CartStatus> Tbl_CartStatus { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Member> Tbl_Member { get; set; }
        public virtual DbSet<Tbl_MemberRole> Tbl_MemberRole { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_ShippingDetail> Tbl_ShippingDetail { get; set; }
        public virtual DbSet<Tbl_SlideImage> Tbl_SlideImage { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    
        public virtual ObjectResult<GetBySearch_Result> GetBySearch(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBySearch_Result>("GetBySearch", searchParameter);
        }
    
        public virtual ObjectResult<SpGet_Tbl_Member_By_ID_Result> SpGet_Tbl_Member_By_ID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGet_Tbl_Member_By_ID_Result>("SpGet_Tbl_Member_By_ID", idParameter);
        }
    
        public virtual ObjectResult<SpGet_Tbl_Member_FirstName_And_EmailId_Result> SpGet_Tbl_Member_FirstName_And_EmailId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGet_Tbl_Member_FirstName_And_EmailId_Result>("SpGet_Tbl_Member_FirstName_And_EmailId");
        }
    
        public virtual int spGetTbl_Member_CountBy_FirstName(string firstName, ObjectParameter memberCount)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetTbl_Member_CountBy_FirstName", firstNameParameter, memberCount);
        }
    
        public virtual int spGetTbl_Product_CountBy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetTbl_Product_CountBy");
        }
    }
}
